# Generated by Django 5.0 on 2023-12-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_remove_vendor_id_alter_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to='vendorapp.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to='vendorapp.vendor'),
        ),
    ]
