# Generated by Django 5.0 on 2023-12-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0004_alter_historicalperformance_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapp.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapp.vendor'),
        ),
    ]
