# Generated by Django 5.0 on 2023-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0006_rename_id_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
